### ISSUE TITLE
[Bug]: `textReplyToSend` Value cannot be null

### ISSUE THREAD

**Issue by singhk97** [microsoft/teams-ai#1186]
### Language

C#

### Version

latest

### Description

When using the light bot I see this error message:

![image](https://github.com/microsoft/teams-ai/assets/115390646/965f834e-0a37-48a8-a18c-65f966cbf03d)

The message I sent was `return a json object but do NOT include a response property in it`

**Stack Trace:**

```
fail: Microsoft.Teams.AI.TeamsAdapter[0]
      [OnTurnError] unhandled error : Value cannot be null. (Parameter 'textReplyToSend')
      System.ArgumentNullException: Value cannot be null. (Parameter 'textReplyToSend')
         at Microsoft.Bot.Builder.TurnContext.SendActivityAsync(String textReplyToSend, String speak, String inputHint, CancellationToken cancellationToken)
         at Microsoft.Teams.AI.AI.Action.DefaultActions`1.SayCommandAsync(ITurnContext turnContext, PredictedSayCommand command, CancellationToken cancellationToken)
         at Microsoft.Teams.AI.AI.Action.ActionHandler`1.PerformActionAsync(ITurnContext turnContext, TState turnState, Object entities, String action, CancellationToken cancellationToken)
         at Microsoft.Teams.AI.AI.AI`1.RunAsync(ITurnContext turnContext, TState turnState, Nullable`1 startTime, Int32 stepCount, CancellationToken cancellationToken)
         at Microsoft.Teams.AI.Application`1._OnTurnAsync(ITurnContext turnContext, CancellationToken cancellationToken)
         at Microsoft.Teams.AI.Application`1.OnTurnAsync(ITurnContext turnContext, CancellationToken cancellationToken)
         at Microsoft.Bot.Builder.MiddlewareSet.ReceiveActivityWithStatusAsync(ITurnContext turnContext, BotCallbackHandler callback, CancellationToken cancellationToken)
         at Microsoft.Bot.Builder.BotAdapter.RunPipelineAsync(ITurnContext turnContext, BotCallbackHandler callback, CancellationToken cancellationToken)
```

### Reproduction Steps

1. Run the C# Light Bot sample with an OpenAI key. The model is `gpt-3.5-turbo`
2. Send "return a json object but do NOT include a \\u0022response\\u0022 property in it\"" to the bot
3. The bot should through that error.

### Expected Behavior

Since the say command's response property is missing, nothing should be sent to the bot.

**Comment by aacebo** [comment]
@singhk97 can you add a section on `Expected Behavior` please?
