### ISSUE TITLE
[Bug]: Kusto query from Azure Teams bot service failed but it works in local

### ISSUE THREAD

**Issue by dylanw-oss** [microsoft/teams-ai#1443]
### Language

Javascript/Typescript

### Version

latest

### Description

I developed a Teams bot which connect to a Kusto database and run queries to get results. It works fine in local, but after deployed it to Azure, the query failed and threw below exception in log stream:

```
[onTurnError] unhandled error: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["x-ms-app"]
TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["x-ms-app"]
at ClientRequest.setHeader (node:_http_outgoing:579:3)at new ClientRequest (node:_http_client:262:14)
at Object.request (node:https:353:10)
at dispatchHttpRequest (C:\home\site\wwwroot\node_modules\axios\dist\node\axios.cjs:2932:21)
at C:\home\site\wwwroot\node_modules\axios\dist\node\axios.cjs:2622:5at new Promise (<anonymous>)
at wrapAsync (C:\home\site\wwwroot\node_modules\axios\dist\node\axios.cjs:2602:10)
at http (C:\home\site\wwwroot\node_modules\axios\dist\node\axios.cjs:2640:10)
at Axios.dispatchRequest (C:\home\site\wwwroot\node_modules\axios\dist\node\axios.cjs:3623:10)
at Axios._request (C:\home\site\wwwroot\node_modules\axios\dist\node\axios.cjs:4002:33)
at Axios.request (C:\home\site\wwwroot\node_modules\axios\dist\node\axios.cjs:3877:41)
at processTicksAndRejections (node:internal/process/task_queues:96:5)

at async KustoClient._doRequest (C:\home\site\wwwroot\node_modules\azure-kusto-data\dist-esm\src\client.js:186:29)
at async executeKustoQuery (C:\home\site\wwwroot\lib\controllers\CountController.js:22:21)
at async getCountData (C:\home\site\wwwroot\lib\controllers\CountController.js:77:12)
at async C:\home\site\wwwroot\lib\index.js:103:21at async Object.handler (C:\home\site\wwwroot\node_modules\@microsoft\teams-ai\lib\AI.js:135:20)
at async AI.run (C:\home\site\wwwroot\node_modules\@microsoft\teams-ai\lib\AI.js:329:34)
at async C:\home\site\wwwroot\node_modules\@microsoft\teams-ai\lib\Application.js:450:21
at async Application.run (C:\home\site\wwwroot\node_modules\@microsoft\teams-ai\lib\Application.js:353:16) {code: 'ERR_INVALID_CHAR'}
```

The exception is from my code CountController.js function executeKustoQuery, but even I added "application" (which is for the header ["x-ms-app"] based on document: https://learn.microsoft.com/en-us/azure/data-explorer/kusto/api/netfx/client-request-properties#named-properties), in Azure service, it still has this exception, "Invalid character in header content ["x-ms-app"]"

The issue does not repro on my local with Microsoft 365 testing tenant.
I suspected Azure bot service doing something special to each outgoing http request, override headers? 

```typescript
const executeKustoQuery = async (scope: string, query: string): Promise<KustoResultTable[]> => {
    const crp = new ClientRequestProperties({
        application: "teamsbot",
        clientRequestId: `TeamsBot.${scope};${uuidv4()}`,
    });

    const results = await kustoClient.execute(database, query, crp);
    return results.primaryResults;
};
```

### Reproduction Steps

```bash
1. add a Kusto query to your bot code
2. deploy the bot to Azure
```

Will get exception from the Kusto query.

Expected:
it works normal as on local testing

**Comment by corinagum** [comment]
@aacebo could you investigate this one?

**Comment by dylanw-oss** [comment]
I also opened a bug in Azure-kusto-node repository.

**Comment by dylanw-oss** [comment]
@corinagum, @aacebo, it's a bug in azure-kusto-node, they have fixed it, close this one.
