### ISSUE TITLE
[Bug]: Samples don't work with node version 18.

### ISSUE THREAD

**Issue by Stevenic** [microsoft/teams-ai#180]
**Please note: any submissions with insufficient reproducible information will be marked as 'Waiting for customer input' and may be closed is there is no response**

**Describe the bug**

The samples fail to run when using the latest version of NodeJS. The issue is restify throws an exception. Upgrading to restify 10 or greater fixes the issue but also requires a minor change to the samples code wise.  We should upgrade all the samples to use the latest version of Restify (11.1.0.)  A new `next` parameter is required for rout handlers so we have to update the `/api/message` handler as shown below.

![image](https://github.com/microsoft/teams-ai/assets/698939/8eaa9d9e-d1bc-46c9-8446-29cccf411cc4)

**Comment by tsubakimoto** [comment]
I ran [04.ai.a.teamsChefBot](https://github.com/microsoft/teams-ai/tree/main/js/samples/04.ai.a.teamsChefBot) on node v18 with this error.

```
> teamschef-demo@1.0.0 dev:teamsfx
> env-cmd --silent -f .localSettings yarn dev

yarn run v1.22.19
$ nodemon --watch ./src --exec node --inspect=9239 --signal SIGINT -r ts-node/register ./src/index.ts
[nodemon] 1.19.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching dir(s): src\**\*
[nodemon] watching extensions: ts,json
[nodemon] starting `node --inspect=9239 -r ts-node/register ./src/index.ts`
Debugger listening on ws://127.0.0.1:9239/60de0cef-e726-4090-b289-1a8c44117461
For help, see: https://nodejs.org/en/docs/inspector
C:\Users\yuta\source\github\teams\teams-ai\js\samples\04.ai.a.teamsChefBot\node_modules\restify\lib\request.js:848
    Request.prototype.closed = function closed() {
                             ^
TypeError: Cannot set property closed of #<Readable> which has only a getter
    at patch (C:\Users\yuta\source\github\teams\teams-ai\js\samples\04.ai.a.teamsChefBot\node_modules\restify\lib\request.js:848:30)
    at Object.<anonymous> (C:\Users\yuta\source\github\teams\teams-ai\js\samples\04.ai.a.teamsChefBot\node_modules\restify\lib\server.js:33:1)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Object.require.extensions.<computed> [as .js] (C:\Users\yuta\source\github\teams\teams-ai\js\samples\04.ai.a.teamsChefBot\node_modules\ts-node\src\index.ts:1608:43)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Function.Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (C:\Users\yuta\source\github\teams\teams-ai\js\samples\04.ai.a.teamsChefBot\node_modules\restify\lib\index.js:10:14)
[nodemon] app crashed - waiting for file changes before starting...
```

This error did not occur with node v16.
