### ISSUE TITLE
[Bug]: feedback_loop error

### ISSUE THREAD

**Issue by jamiesun** [microsoft/teams-ai#2061]
### Language

Python

### Version

latest

### Description

```python
@bot_app.feedback_loop
async def on_feedback_loop(
    context: TurnContext, state: AppTurnState, feedback_data: FeedbackLoopData
):
    print(feedback_data)
```

Exception: 

```DEBUG:httpx:load_ssl_context verify=True cert=None trust_env=True http2=False
DEBUG:httpx:load_verify_locations cafile='/Volumes/ExtDISK/github/TeamsBot/.venv/lib/python3.11/site-packages/certifi/cacert.pem'
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.11/3.11.8/Frameworks/Python.framework/Versions/3.11/lib/python3.11/runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.8/Frameworks/Python.framework/Versions/3.11/lib/python3.11/runpy.py", line 88, in _run_code
    exec(code, run_globals)
  File "/Users/wangjuntao/.vscode/extensions/ms-python.debugpy-2024.10.0-darwin-arm64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/Users/wangjuntao/.vscode/extensions/ms-python.debugpy-2024.10.0-darwin-arm64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/Users/wangjuntao/.vscode/extensions/ms-python.debugpy-2024.10.0-darwin-arm64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/Users/wangjuntao/.vscode/extensions/ms-python.debugpy-2024.10.0-darwin-arm64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/wangjuntao/.vscode/extensions/ms-python.debugpy-2024.10.0-darwin-arm64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Users/wangjuntao/.vscode/extensions/ms-python.debugpy-2024.10.0-darwin-arm64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/Volumes/ExtDISK/github/TeamsBot/src/app.py", line 3, in <module>
    from api import api as app
  File "/Volumes/ExtDISK/github/TeamsBot/src/api.py", line 6, in <module>
    from teamsbot import bot_app
  File "/Volumes/ExtDISK/github/TeamsBot/src/teamsbot.py", line 257, in <module>
    @bot_app.feedback_loop
     ^^^^^^^^^^^^^^^^^^^^^
TypeError: Application.feedback_loop() takes 1 positional argument but 2 were given
```

### Reproduction Steps

```bash
1.Define the event code
2.Start debugging
```

**Comment by SubbaReddi** [comment]
@jamiesun:
Can you try updating @bot_app.feedback_loop to @bot_app.feedback_loop()

**Comment by jamiesun** [comment]
It does work after the modification
It is recommended that the code comments should also be modified, which is easy to mislead

···python

    def feedback_loop(
        self,
    ) -> Callable[
        [Callable[[TurnContext, StateT, FeedbackLoopData], Awaitable[None]]],
        Callable[[TurnContext, StateT, FeedbackLoopData], Awaitable[None]],
    ]:
        """
        Registers a handler for feedback loop events when a user clicks the thumbs
        up or down button on a response from AI.
        enable_feedback_loop must be set to true in the AI Module.
         ```python
        # Use this method as a decorator
        @app.feedback_loop
        async def feedback_loop(
            context: TurnContext, state: TurnState, feedback_data: FeedbackLoopData
        ):
            print(feedback_data)
        # Pass a function to this method
        app.feedback_loop()(feedback_loop)
        ```
        """

        def __selector__(context: TurnContext) -> bool:
            return (
                context.activity.type == ActivityTypes.invoke
                and context.activity.name == "message/submitAction"
                and isinstance(context.activity.value, dict)
                and context.activity.value.get("actionName") == "feedback"
            )

        def __call__(
            func: Callable[[TurnContext, StateT, FeedbackLoopData], Awaitable[None]],
        ) -> Callable[[TurnContext, StateT, FeedbackLoopData], Awaitable[None]]:
            async def __handler__(context: TurnContext, state: StateT):
                if not context.activity.value:
                    return False

                activity_value: dict = context.activity.value
                feedback = FeedbackLoopData.from_dict(
                    {
                        **activity_value,
                        "reply_to_id": context.activity.reply_to_id,
                    }
                )

                await func(context, state, feedback)
                await context.send_activity(
                    Activity(
                        type=ActivityTypes.invoke_response,
                        value=InvokeResponse(status=200, body={}),
                    )
                )
                return True

            self._routes.append(Route[StateT](__selector__, __handler__, True))
            return func

        return __call__
···

**Comment by SubbaReddi** [comment]
Updated https://github.com/microsoft/teams-ai/blob/main/getting-started/CONCEPTS/POWERED-BY-AI.md#python-1
