### ISSUE TITLE
[Bug]: samples/04.ai-apps/a.teamsChefBot [nodemon] app crashed - waiting for file changes before starting...

### ISSUE THREAD

**Issue by haidv1992** [microsoft/teams-ai#2097]
### Language

Javascript/Typescript

### Version

latest

### Description

![image](https://github.com/user-attachments/assets/6622de37-20ab-4f8e-afe9-7e5e9d1f1190)

### Reproduction Steps
i use node 18

https://github.com/user-attachments/assets/cc048bee-e1c3-4eaa-9a87-241ee77cca93

Error [ERR_UNKNOWN_BUILTIN_MODULE]: No such built-in module: node:stream/web
    at new NodeError (internal/errors.js:322:7)
    at Function.Module._load (internal/modules/cjs/loader.js:781:13)
    at Module.require (internal/modules/cjs/loader.js:1003:19)
    at require (internal/modules/cjs/helpers.js:107:18)
    at Object.<anonymous> (/Users/hnguyenduc/TeamsApps/teams-chef-bot/node_modules/openai/src/_shims/node-runtime.ts:16:1)
    at Module._compile (internal/modules/cjs/loader.js:1114:14)
    at Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Object.require.extensions.<computed> [as .js] (/Users/hnguyenduc/TeamsApps/teams-chef-bot/node_modules/ts-node/src/index.ts:1608:43)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12) {
  code: 'ERR_UNKNOWN_BUILTIN_MODULE'
}
[nodemon] app crashed - waiting for file changes before starting...

**Comment by SubbaReddi** [comment]
@haidv1992 : Tried to reproduce the issue with node v18.20.4, but issue is not reproducible.
Can you download latest repository from [github](https://github.com/microsoft/teams-ai/tree/main/js/samples/04.ai-apps/a.teamsChefBot) and validate?

**Comment by corinagum** [comment]
Closing due to lack of activity.
