### ISSUE TITLE
[Bug]: In running listBot-streaming sample

### ISSUE THREAD

**Issue by duydl** [microsoft/teams-ai#2251]
### Language

Python

### Version

latest

### Using OpenAI API
I had the folllowing error when running the python listBot-streaming sample, using `default_model="gpt-4o-mini"`. 

```
stream_id is not a known attribute of class <class 'botbuilder.schema._models_py3.Entity'> and will be ignored
stream_sequence is not a known attribute of class <class 'botbuilder.schema._models_py3.Entity'> and will be ignored
stream_type is not a known attribute of class <class 'botbuilder.schema._models_py3.Entity'> and will be ignored
TEST <msrest.universal_http.async_requests.AsyncRequestsClientResponse object at 0x7618746baf30>
Task exception was never retrieved
future: <Task finished name='Task-14' coro=<StreamingResponse.drain_queue.<locals>._drain_queue() done, defined at /home/duydl/Projects/teams/teams-ai/python/packages/ai/teams/streaming/streaming_response.py:251> exception=ErrorResponseException('(BadSyntax) Only start streaming and continue streaming types are allowed as a typing activity')>
Traceback (most recent call last):
  File "/home/duydl/Projects/teams/teams-ai/python/packages/ai/teams/streaming/streaming_response.py", line 262, in _drain_queue
    await self.send_activity(activity)
  File "/home/duydl/Projects/teams/teams-ai/python/packages/ai/teams/streaming/streaming_response.py", line 306, in send_activity
    response = await self._context.send_activity(activity)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/duydl/Projects/teams/botbuilder-python/libraries/botbuilder-core/botbuilder/core/turn_context.py", line 174, in send_activity
    result = await self.send_activities([activity_or_text])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/duydl/Projects/teams/botbuilder-python/libraries/botbuilder-core/botbuilder/core/turn_context.py", line 226, in send_activities
    return await self._emit(self._on_send_activities, output, logic())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/duydl/Projects/teams/botbuilder-python/libraries/botbuilder-core/botbuilder/core/turn_context.py", line 304, in _emit
    return await logic
           ^^^^^^^^^^^
  File "/home/duydl/Projects/teams/botbuilder-python/libraries/botbuilder-core/botbuilder/core/turn_context.py", line 221, in logic
    responses = await self.adapter.send_activities(self, output)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/duydl/Projects/teams/botbuilder-python/libraries/botbuilder-core/botbuilder/core/cloud_adapter_base.py", line 93, in send_activities
    response = await connector_client.conversations.reply_to_activity(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/duydl/Projects/teams/botbuilder-python/libraries/botframework-connector/botframework/connector/aio/operations_async/_conversations_operations_async.py", line 529, in reply_to_activity
    raise models.ErrorResponseException(self._deserialize, response)
botbuilder.schema._models_py3.ErrorResponseException: (BadSyntax) Only start streaming and continue streaming types are allowed as a typing activity
```

### Using Azure OpenAI API

When using Azure. I also had this error:

```
Traceback (most recent call last):
  File "/home/duydl/Projects/teams/teams-ai/python/samples/04.ai.d.chainedActions.listBot/.conda/lib/python3.11/site-packages/teams/app.py", line 758, in _on_turn
    if not await self._run_ai_chain(context, state):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/duydl/Projects/teams/teams-ai/python/samples/04.ai.d.chainedActions.listBot/.conda/lib/python3.11/site-packages/teams/app.py", line 836, in _run_ai_chain
    is_ok = await self._ai.run(context, state)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/duydl/Projects/teams/teams-ai/python/samples/04.ai.d.chainedActions.listBot/.conda/lib/python3.11/site-packages/teams/ai/ai.py", line 146, in run
    plan = await self.planner.begin_task(context, state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/duydl/Projects/teams/teams-ai/python/samples/04.ai.d.chainedActions.listBot/.conda/lib/python3.11/site-packages/teams/ai/planners/action_planner.py", line 100, in begin_task
    return await self.continue_task(context, state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/duydl/Projects/teams/teams-ai/python/samples/04.ai.d.chainedActions.listBot/.conda/lib/python3.11/site-packages/teams/ai/planners/action_planner.py", line 111, in continue_task
    raise ApplicationError(res.error or "[ActionPlanner]: failed task")
teams.app_error.ApplicationError: 
                The chat completion API returned an error
                status of None: Error code: 400 - {'error': {'message': 'Unrecognized request argument supplied: parallel_tool_calls', 'type': 'invalid_request_error', 'param': None, 'code': None}}
```

I found that it is related to this issue https://github.com/Azure/azure-rest-api-specs/issues/29545 and some other samples e.g `listBot` also raised this.  I managed to bypass this by modifying `async def complete_prompt` method in `class OpenAIModel(PromptCompletionModel)`.

### Reproduction Steps

```bash
1. Follow instruction in https://github.com/microsoft/teams-ai/tree/main/python/samples/04.ai.h.chainedActions.listBot-streaming
2. (Optional) Clone the repo and install packages/ai in editable mode to debug. 
3. Press F5. Add app to Team. 
4. Send a message. Error happens.
```

**Comment by sayali-MSFT** [comment]
Hello @duydl ,Thank you for bringing this issue to our attention. We will look into it and get back to you shortly.

**Comment by sayali-MSFT** [comment]
Hello @duydl , Thank you for your patience! We have reported this as a bug for further investigation. 

We will keep you updated as soon as we receive further information. Thank you for bringing this to our attention!

**Comment by SubbaReddi** [comment]
I can reproduce the issue as described above.

**Comment by lilyydu** [comment]
Hi @duydl, 

We have resolved this bug within this [PR](https://github.com/microsoft/teams-ai/pull/2205)- will be available in the upcoming Python release. Thanks for your patience! Please re-open if you do encounter the related bugs following the release.

**Comment by saichaitanya1729** [comment]
Hi @lilyydu,

Thanks for the fix provided. The issue "(BadSyntax) Only start streaming and continue streaming types are allowed as a typing activity" is fixed with the changes in the above PR. But I have an issue with streaming the response.

I was getting a list index out of range error when it is trying to give back a response. This was because the choices in the first chunk was empty. I was able to bypass this error by making some changes in the openai_model.py file.

async for chunk in completion:
    if not chunk.choices:
        continue
    delta = chunk.choices[0].delta

After these changes, I am able to get back responses from the listbot but it is not streaming. I get back the entire response at once instead of streaming chunks. 
The "stream" argument in AzureOpenAIModelOptions is set as 'True'. Is there something else I am missing in the code to allow it to stream?

**Comment by lilyydu** [comment]
Hi @saichaitanya1729,

Skipping the choices in the first chunk will end up bypassing streaming. Can you double check if you have configured things properly listed on this [doc](https://github.com/microsoft/teams-ai/blob/main/getting-started/CONCEPTS/STREAMING.md)?

**Comment by lilyydu** [comment]
@saichaitanya1729 

I noticed you have tools augmentation configured with streaming- right now that is not currently available for Python. We do have this item in progress, however, will comment on this thread once we have a PR ready

**Comment by saichaitanya-informa** [comment]
@lilyydu Thanks for the update. 

I have the same issue if I use a custom model, I get an empty box at first and then it gives the entire response on the teams chat without streaming. 
I followed instructions and instantiated the StreamingResponse class to stream responses.

Can I assume the streaming is not happening because of the same reason?

Code:
`async def stream_llm_response(turn_context: TurnContext, prompt):
    streaming_response = StreamingResponse(turn_context)
    try:
        async for chunk in agent_wrapper(turn_context=turn_context, prompt=prompt):
            logging.info(f"{chunk}", end="|")
            if chunk:
                streaming_response.queue_text_chunk(chunk)  # Stream each chunk immediately
                
        await streaming_response.end_stream()  # End the stream after all chunks are sent

    except Exception as e:
        logging.error(f"Error during streaming: {e}")

async def on_message_activity(self, turn_context: TurnContext):
        await turn_context.send_activity(Activity(type=ActivityTypes.typing))
        turn_context.remove_recipient_mention(turn_context.activity)
        text = turn_context.activity.text
        if text:
            await stream_llm_response(turn_context, text)
        else:
            await turn_context.send_activity("Something went wrong, please try again.")`

**Comment by saichaitanya1729** [comment]
@lilyydu Thanks for the update.

I have the same issue if I use a custom model, I get an empty box at first and then it gives the entire response on the teams chat without streaming.
I followed instructions and instantiated the StreamingResponse class to stream responses.

Can I assume the streaming is not happening because of the same reason?

Code used:

async def stream_llm_response(turn_context: TurnContext, prompt):
streaming_response = StreamingResponse(turn_context)
try:
async for chunk in agent_wrapper(turn_context=turn_context, prompt=prompt):
logging.info(f"{chunk}")
if chunk:
streaming_response.queue_text_chunk(chunk) # Stream each chunk immediately
await streaming_response.end_stream() # End the stream after all chunks are sent
except Exception as e:
logging.error(f"Error during streaming: {e}")

async def on_message_activity(self, turn_context: TurnContext):
await turn_context.send_activity(Activity(type=ActivityTypes.typing))
turn_context.remove_recipient_mention(turn_context.activity)
text = turn_context.activity.text
if text:
await stream_llm_response(turn_context, text)
else:
await turn_context.send_activity("Something went wrong, please try again.")

**Comment by saichaitanya1729** [comment]
@lilyydu This is Teams on the webclient.
 I just checked it on desktop and the streaming seems to be working. Is there a known limitation on the web and the mobile clients?

**Comment by lilyydu** [comment]
Hi @saichaitanya1729,

There previously was a bug on the web client but this is rooted to Teams Client (separate from AI SDK). I will escalate this to the right contact and let you know once its fixed. In the meantime, please try to stick with desktop.

**Comment by SolangeAO** [comment]
Hello @saichaitanya1729, could you please share the Desktop version and Web version you are using (Settings > About Teams)? It would be helpful as well if you could collect the support files and provide that information to us (See: https://learn.microsoft.com/en-us/microsoftteams/log-files#log-collection). Thanks!

**Comment by saichaitanya1729** [comment]
Thank you @lilyydu. 

Hi @SolangeAO, these are the versions I am using.

Web client:
Version
The client version is 1415/24120100221.

Desktop:
Version
You have Microsoft Teams version 25007.607.3371.8436.
You've got the latest version. It was last checked on 1/28/2025.
AVD SlimCore Media Optimized.
The client version is 49/25010620408.

Mobile:
Version: 6.23.1
Build: 6.23.77.2024234701/0104 
Calling Version: 2024.44.01.12
Release Branch: 2024Dec-T1

As for the logs, I collected them, but what would be the best way to share those across with you?

**Comment by lilyydu** [comment]
@saichaitanya1729 No worries, it will be sometime next week (definitely before Friday the 7th)!

**Comment by saichaitanya1729** [comment]
Hi @SolangeAO, Hope you are doing well. Could you please share any updates on the streaming bug affecting the web and mobile clients? Thank you.

**Comment by PieterT2000** [comment]
Any updates on this?

**Comment by SolangeAO** [comment]
@saichaitanya1729 @PieterT2000  The client team is looking currently into this one. Will communicate any updates when I've got one. Thank you for your patience!

**Comment by corinagum** [comment]
Thanks for raising this. This is the previous-generation Teams AI library, which has been retired in favor of the new Teams SDK, so we're not planning further development here. See the migration guide to move over: https://microsoft.github.io/teams-sdk/python/migrations/v1/. Closing this out.
